language: java

services:
  - docker

before_install:
  - docker pull adoptopenjdk/openjdk11:jdk-11.0.3.7
  - docker pull clojure:openjdk-13-lein 
  - docker pull elixir:1.11


script:
  - docker run --rm -it -v $TRAVIS_BUILD_DIR/1_ThreadsAndLocks:/1_ThreadsAndLocks -w /1_ThreadsAndLocks adoptopenjdk/openjdk11:jdk-11.0.3.7 ./gradlew build
  - docker run --rm -it --memory=4g -p 3000:3000 -v $TRAVIS_BUILD_DIR/2_FunctionalProgramming/:/2_FunctionalProgramming/ -w /2_FunctionalProgramming/ clojure:openjdk-13-lein lein test
  - docker run --rm -it --memory=4g -v $TRAVIS_BUILD_DIR/3_Clojure/clojure-way/:/3_Clojure/clojure-way/ -w /3_Clojure/clojure-way/ clojure:openjdk-13-lein lein test
  - docker run --rm -it -v $TRAVIS_BUILD_DIR/4_Actors_Elixir/actors:/4_Actors_Elixir/actors -w /4_Actors_Elixir/actors elixir:1.11 mix test --trace
  - docker run --rm -it -v $TRAVIS_BUILD_DIR/4_Actors_Elixir/cache:/4_Actors_Elixir/cache -w /4_Actors_Elixir/cache elixir:1.11 mix test --trace
  - docker run --rm -it -v $TRAVIS_BUILD_DIR/4_Actors_Elixir/cache_gen_server:/4_Actors_Elixir/cache_gen_server -w /4_Actors_Elixir/cache_gen_server elixir:1.11 mix test --trace
  - docker run --rm -it -v $TRAVIS_BUILD_DIR/4_Actors_Elixir/word_count:/4_Actors_Elixir/word_count -w /4_Actors_Elixir/word_count elixir:1.11 mix compile
  - docker run --rm -it --memory=4g -v $TRAVIS_BUILD_DIR/5_Communicating_Sequential_Processes/channels/:/5_Communicating_Sequential_Processes/channels/ -w /5_Communicating_Sequential_Processes/channels/ clojure:openjdk-13-lein lein test


  